codelion/optillm

- plansearch.py
> chore: update plansearch.py

- Dockerfile
- README.md
- docker-compose.yaml
- optillm.py
Neat project!
I wanted to make some changes and thought I'd submit them to you in a PR, totally understand if you're not interested in them though - if that's the case feel free to close the PR.
- Feat: Add Dockerfile for container builds.
- Feat: Add Docker Compose example.
- Feat: Add optional authentication to the optillm proxy.
- Feat: Add the option of configuring optillm via environment variables.
- Feat: Add basic /health endpoint.
- Docs: Add documentation for running with Docker.
- Docs: Add documentation for args.
- Fix: Clean up mix of - and _ in args, handle old _ args for backwards compatibility.
- Fix: Minor linting in readme.
- Chore: Move arg parsing out of main to it's own class.
> feat(docker,auth): Add Docker, Compose, Auth, Parameter envs

- optillm.py
Small hotfix to follow up from #6, don't require api key for /health endpoint.
> fix(healthcheck): dont require api key for /health

- README.md
Added note to the Readme file about the correct way to set the model attribute in a client request.
> Added note to about the correct way to set the model attribute in a client request.

- README.md
- optillm.py
- requirements.txt
The user can use the Azure CLI to login, then the key is not needed anymore. 
Feel free to squash.
> Azure Managed Identity support (entra)

- README.md
- optillm.py
- optillm/reread.py
Implements the paper "Re-Reading Improves Reasoning in Large Language Models" but the results on livebench are mixed:
########## All Groups ##########
category                      average  coding  data_analysis  instruction_following  language  math  reasoning
model                                                                                                         
gpt-4o-mini-2024-07-18           44.1    42.5           42.7                   65.4      33.8  44.1       36.0
re2-gpt-4o-mini-2024-07-18       43.4    40.9           46.4                   68.6      35.8  42.3       26.7
> Feat implement reread

- README.md
I've added a new section to the installation guide that provides step-by-step commands for running the proxy with a local server, specifically llama.cpp.
> Added local server setup to `installation` section

- optillm/cot_decoding.py
probs.size() should take in dimension -1 instead of 1
Resolves #45
> Fix confidence calculation

- optillm.py
Added --log flag in cli arguments to set log level for issue #44
> Add cli log flag

- optillm.py
- optillm/plugins/router_plugin.py
- scripts/train_optillm_classifier.py
Add router plugin that takes an effort value (0-1) and then routes the request to the best possible approach based on the prompt.
> Feat router

- optillm/entropy_decoding.py
- optillm/litellm_wrapper.py
- setup.py
- Removed softmax from attention metrics calculation for entropy_decoding. see https://x.com/tensorqt/status/1850545336449675579 
- Handle safety_settings in litellm wrapper so that it is added only for gemini models
> Fix litellm wrapper for claude

- README.md
- optillm.py
- optillm/inference.py
- setup.py
- Ability to use local built-in inference server
- Allows logprobs in output responses (this is not supported in ollama)
- Allows multiple response sampling (this is not supported in ollama)
- Supports multiple LoRAs (this is not supported in ollama)
- Supports prompt caching
- Supports alternative decoding techniques like cot_decoding and entropy_decoding
> Feat add local inference

- Dockerfile
- optillm.py
- optillm/plugins/readurls_plugin.py
- setup.py
> Fix dockerfile arm and streaming responses

- optillm.py
- requirements.txt
- setup.py
Fixes #9 by adding a simple chat inference for running with proxy.
> Fix add simple gui

- optillm.py
- optillm/__init__.py
- optillm/plugins/readurls_plugin.py
- optillm/plugins/router_plugin.py
- scripts/eval_aime_benchmark.py
- scripts/requirements.txt
- scripts/train_optillm_classifier.py
- setup.py
- fix version to be consistent across the code
> Add new modernbert based router in plugin

- .gitignore
- optillm.py
- optillm/inference.py
- optillm/plugins/json_plugin.py
- optillm/plugins/thinkdeeper_plugin.py
- optillm/thinkdeeper.py
- requirements.txt
- scripts/eval_aime_benchmark.py
- scripts/eval_math500_benchmark.py
- scripts/eval_optillmbench.py
- scripts/gen_optillmbench.py
- scripts/requirements.txt
- setup.py
- Add support to generate JSON from any model using OpenAI compatible pydantic types or jsonschema.
- Add support for reasoning_effort, you can use it with deepseek r1 models.
- Simplify local inference and support flash-atten 2 the local inference now works with very little degradation in performance when compared to vllm for requests that are not batched.
> Feat add json plugin and support low, medium, high reasoning efforts for thinking models

- optillm.py
- optillm/__init__.py
- optillm/plugins/mcp_plugin.py
- requirements.txt
- setup.py
- Add support for streaming responses in local inference mode
- Add mcp client plugin, this enables you to talk to any mcp server using any LLM
- Fix gradio GUI regression
> Feat add mcp plugin again

- README.md
- optillm/cepo/README.md
- optillm/cepo/cepo.py
- optillm/cepo/configs/cepo_config.yaml
* Add plan diversity mechanism in CePO
* Update rating prompt in CePO
* Update README to include plan diversity and new results
* Minor fixes and improvements to CePO
> Add plan diversity and update rating prompt in CePO

- optillm/__init__.py
- scripts/eval_aime_benchmark.py
- setup.py
> Cepo 1.1 fixes

- README.md
- optillm/__init__.py
- setup.py
> bump version for new release

- README.md
- optillm/__init__.py
- optillm/autothink/README.md
- optillm/autothink/__init__.py
- optillm/autothink/autothink.py
- optillm/autothink/classifier.py
- optillm/autothink/example.py
- optillm/autothink/processor.py
- optillm/autothink/steering.py
- optillm/inference.py
- requirements.txt
- setup.py
- Add the autothink decoding
- Use adaptive-classifier for routing
- Use pts steering vectors
> Feat autothink decoding

- optillm/__init__.py
- optillm/plugins/coc_plugin.py
- setup.py
- Run CoC plugin in notebook for isolation
> Fix coc execution

- optillm/__init__.py
- optillm/inference.py
- scripts/eval_math500_benchmark.py
- setup.py
Added '-mlx-' to the list of MLX model patterns in should_use_mlx for broader matching. Reduced max_tokens from 32768 to 8192 in get_llm_response within eval_math500_benchmark.py to limit token usage.
> Update MLX model patterns and reduce max_tokens in eval script

- optillm/__init__.py
- optillm/bon.py
- optillm/inference.py
- optillm/moa.py
- optillm/plugins/majority_voting_plugin.py
- optillm/thinkdeeper_mlx.py
- scripts/eval_aime_benchmark.py
- scripts/eval_optillmbench.py
- setup.py
Introduces a plugin that generates multiple candidate solutions using the OpenAI API and selects the most frequent answer via majority voting. Includes answer extraction, normalization, and a summary of the voting process. Useful for tasks with discrete answers such as math, coding, and multiple choice problems.
fixes #201 
superseeds #83
> Add majority voting plugin for candidate selection

- optillm/plugins/json_plugin.py
- pyproject.toml
- tests/test_json_plugin.py
> Feat upgrade outlines

- optillm/deepconf/README.md
- optillm/deepconf/__init__.py
- optillm/deepconf/confidence.py
- optillm/deepconf/deepconf.py
- optillm/deepconf/processor.py
- optillm/inference.py
- tests/test_deepconf.py
- initial deepconf implementation
> Feat add deepconf

- optillm/__init__.py
- optillm/plugins/privacy_plugin.py
- pyproject.toml
- tests/test_privacy_plugin_performance.py
Refactored privacy_plugin to use singleton instances for AnalyzerEngine and AnonymizerEngine, preventing repeated initialization and improving performance. Added tests to verify resource caching, singleton reuse, and performance across multiple invocations.
Fixes #253
> Cache expensive resources in privacy plugin
